### PR TITLE
Implementation: Name audio files according to their messages

### PR DESCRIPTION
**Pull request by evilneuro**
This is a quick way to implement #1 

- export Google Sheet as TSV into new directory `announcements-by-content`
- create and run script to parse TSV and create symbolic links to the MP3 files in `announcements`

there's literally no checking to see what's already there, in fact it will force overwrite any existing files or symlinks in `announcement-by-content`, and it's very brittle if there are data quality issues (I had to update the Google sheet to catch a couple of missing entries and file name references), but it does stuff!

### CODE REVIEW

**Comment by matteason** [comment]
This is a brilliant idea, thanks @evilneuro ! I wonder if it would be worth having the script just copy the files rather than do a symlink? That would probably make it easier for people to grab individual files from the GitHub web interface rather than having to clone locally to follow the symlinks. The files aren't huge so I don't think it matters too much if we duplicate them.

**Comment by evilneuro** [comment]
actually yeah that makes more sense, since github is weird about symlinks

**Comment by evilneuro** [comment]
hopefully this looks better from a usefulness point of view!

**Comment by matteason** [comment]
Perfect! :shipit:

**Pull request merged**
